# Generated by Django 4.1.3 on 2022-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlideShow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("shordesc", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
