# Generated by Django 4.1.3 on 2022-11-05 17:01

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("shordesc", models.CharField(max_length=250)),
                ("price", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=backend.models.upload_path
                    ),
                ),
                ("type", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("shordesc", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=backend.models.upload_path
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="SlideShow",),
        migrations.AddField(
            model_name="food",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.foodcategory"
            ),
        ),
    ]
