# Generated by Django 4.1.3 on 2022-11-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_food_foodcategory_delete_slideshow_food_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food", old_name="category_id", new_name="category",
        ),
        migrations.RemoveField(model_name="food", name="shordesc",),
    ]
