# Generated by Django 4.1.3 on 2022-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_rename_category_id_food_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food", name="type", field=models.IntegerField(),
        ),
    ]
