# Generated by Django 4.1.3 on 2022-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_food_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="food", name="category",),
    ]
