# Generated by Django 4.1.3 on 2022-11-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_food_category_alter_food_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="food", name="category",),
    ]
