# Generated by Django 4.1.3 on 2022-11-06 17:23

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_food_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="foodcategory", name="price",),
        migrations.RemoveField(model_name="foodcategory", name="shordesc",),
        migrations.AddField(
            model_name="food",
            name="shordesc",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=backend.models.upload_path
            ),
        ),
        migrations.AlterField(
            model_name="foodcategory",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
