# Generated by Django 4.1.3 on 2022-11-07 23:25

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_remove_food_category_food_category_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteFoods",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("shordesc", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=backend.models.upload_path
                    ),
                ),
            ],
        ),
    ]
