# Generated by Django 4.1.3 on 2022-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_favoritefoods"),
    ]

    operations = [
        migrations.RemoveField(model_name="food", name="type",),
        migrations.AddField(
            model_name="food",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
